replicaCount: 1

image: quay.io/cloud-architecture-workshop/minio:RELEASE.2020-12-29T23-29-29Z

serviceAccount:
  create: true
  name: ""

podSecurityContext: 
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

route:
  enabled: true
  host:
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

resources:
  limits:
    cpu: 200m
    memory: 250Mi
  requests:
    cpu: 100m
    memory: 128Mi

minio:
  accessKey: minio
  secretKey: minio123
  region: us-east-1
  pvc:
    storage: 1Gi
    storageClass: managed-csi

client:
  secret:
    enabled: true
    name: client-s3
